const CACHE='talktalk-v17-home-redesign';const CORE=["./", "./index.html", "./manifest.webmanifest", "./assets/icons/icon-192.png", "./assets/icons/icon-512.png", "./assets/icons/apple-touch-icon.png", "./assets/treasures/treasure-01-gourd.webp", "./assets/treasures/treasure-02-rope.webp", "./assets/treasures/treasure-03-red-bean-porridge.webp", "./assets/treasures/treasure-04-golden-axe.webp", "./assets/treasures/treasure-05-feather-robe.webp", "./assets/treasures/treasure-06-goblin-club.webp", "./assets/treasures/treasure-07-dragon-king-crown.webp", "./assets/treasures/treasure-08-flower-shoe.webp", "./assets/treasures/treasure-09-magpie.webp", "./assets/treasures/treasure-10-lotus.webp", "./assets/treasures/treasure-11-tortoise.webp", "./assets/treasures/treasure-12-grapes.webp", "./assets/treasures/treasure-13-violin.webp", "./assets/treasures/treasure-14-sheep.webp", "./assets/treasures/treasure-15-mouse.webp", "./assets/treasures/treasure-16-cheese.webp", "./assets/treasures/treasure-17-meat.webp", "./assets/treasures/treasure-18-golden-egg.webp", "./assets/treasures/treasure-19-cheese-basket.webp", "./assets/treasures/treasure-20-sun.webp", "./assets/treasures/treasure-21-magic-lamp.webp", "./assets/treasures/treasure-22-sailing-ship.webp", "./assets/treasures/treasure-23-glass-slipper.webp", "./assets/treasures/treasure-24-red-hood.webp", "./assets/treasures/treasure-25-magic-beans.webp", "./assets/treasures/treasure-26-candy-house.webp", "./assets/treasures/treasure-27-red-brick.webp", "./assets/treasures/treasure-28-donkey.webp", "./assets/treasures/treasure-29-boots.webp", "./assets/treasures/treasure-30-king-crown.webp"];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET')return;
 const u=new URL(e.request.url);
 if(u.origin!==location.origin)return;
 if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{let x=r.clone();caches.open(CACHE).then(c=>c.put('./index.html',x));return r}).catch(()=>caches.match('./index.html')));return}
 e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{if(r.ok){let x=r.clone();caches.open(CACHE).then(c=>c.put(e.request,x))}return r})));
});
